#!/bin/bash
# cli1-1.bash

# Vars group

# Points
totalpoints=1
pospoints=2
negpoints=1


# Colors
ERRCOLOR=`tput setaf 1`
QCOLOR=`tput setaf 3`
ANSCOLOR=`tput setaf 2`
OUTCOLOR=`tput setaf 4`
PROMPTCOLOR=`tput setaf 3`
CMDCOLOR=`tput setaf 4`
COLRESET=`tput sgr0`

PROMPT="${COLRESET}codio ~/workspace $ ${COLRESET}"

# Helper funcs
function addpoints {
	totalpoints=$(($totalpoints+$pospoints))
	echo "${PROMPTCOLOR}=>${QCOLOR} Totalpoints: $totalpoints ${COLRESET}"
}
function substractpoints {
	totalpoints=$(($totalpoints-$negpoints))
	echo "${PROMPTCOLOR}=>${QCOLOR} Totalpoints: $totalpoints ${COLRESET}"
}
function changedir {
	cd "$1"
}
function goodbye {
	echo "${PROMPTCOLOR}=>${ANSCOLOR} Good! So far, you've learned the following bash commands:${COLRESET}"
	echo "${PROMPT}${CMDCOLOR}whoami${COLRESET}${ANSCOLOR} for getting the current user${COLRESET}"
	echo "${PROMPT}${CMDCOLOR}pwd${COLRESET}${ANSCOLOR} for getting the current working directory${COLRESET}"
	echo "${PROMPTCOLOR}=>${QQCOLOR} Goodbye! See you on your next challenge!${COLRESET}"
	exit
}

# qa# = question answer #number
function question1 {
	echo "${PROMPTCOLOR}TASK: ${QCOLOR} All right! Remember how to get the 'current user'?:${COLRESET}"
	echo -n "${PROMPT}"
	read -r qa1
	if [[ "$qa1" == "whoami" ]]; then
		echo "${PROMPTCOLOR}=>${ANSCOLOR} That's it! The ${CMDCOLOR}whoami${COLRESET}${ANSCOLOR} command outputs the current logged in user: ${OUTCOLOR}$(whoami)${COLRESET}"
		addpoints
		question2
	else
		echo "${PROMPTCOLOR}ERROR: ${ERRCOLOR} Ehm, the ${CMDCOLOR}$qa1${COLRESET}${ERRCOLOR} command does not output the current user, try again.${COLRESET}"
		substractpoints
		question1
	fi
}

function question2 {
	echo "${PROMPTCOLOR}TASK: ${QCOLOR} Confirm that we've entered by printing the 'path to the working directory':${COLRESET}"
	echo -n "${PROMPT}"
	read -r qa2
	if [[ $qa2 == "pwd" ]]; then
		echo "${PROMPTCOLOR}=>${ANSCOLOR} Our current directory path is ${CMDCOLOR}$(pwd)${COLRESET}${ANSCOLOR}${COLRESET}"
		addpoints
		goodbye
	else
		echo "${PROMPTCOLOR}ERROR: ${ERRCOLOR} I can't recognize the ${CMDCOLOR}$qa2${COLRESET}${ERRCOLOR} command, try again.${COLRESET}"
		substractpoints
		question2
	fi
}








question1